### ISSUE TITLE
Planning: Storyboard

### ISSUE THREAD

**Issue by kaynzhel** [CMPUT301F21T37/Momentum#3]
Description: Diagram storyboard sequences of using your application, with transitions between different states of the user interface, caused by the user manipulating the controls or providing input. Within the diagrams, reference the relevant requirements. Convincingly show all the requirements are covered.

**Comment by Hyan320** [comment]
![habit event change](https://user-images.githubusercontent.com/70993097/137553757-b90f714d-2d6e-41c4-8b43-a58c5cf2aedc.jpg)
![change of habit](https://user-images.githubusercontent.com/70993097/137553768-a3298c95-4053-4461-bc15-101f5f28f913.jpg)
![change for setting](https://user-images.githubusercontent.com/70993097/137553777-1c6f22a9-26e2-4176-9475-64e761275680.jpg)
few changes for completion
